// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX99LYTiNvR65Scpva04KSjQYZ7kk6Xa0',
    appId: '1:550486000364:web:808cf11c275b71bb36dbc9',
    messagingSenderId: '550486000364',
    projectId: 'vrchat-4d279',
    authDomain: 'vrchat-4d279.firebaseapp.com',
    storageBucket: 'vrchat-4d279.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvEjnCMCsPHhFTmjVmJ6odgPDgePwro84',
    appId: '1:550486000364:android:a2205a5be081386836dbc9',
    messagingSenderId: '550486000364',
    projectId: 'vrchat-4d279',
    storageBucket: 'vrchat-4d279.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Se1suny55zU7ipe_7qa1kNLS5jvYh8s',
    appId: '1:550486000364:ios:62aa5033519cbbba36dbc9',
    messagingSenderId: '550486000364',
    projectId: 'vrchat-4d279',
    storageBucket: 'vrchat-4d279.appspot.com',
    iosClientId: '550486000364-p58iabd081rsg1u73jrhpuai0811mkb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
